spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/goorm_bord
    driver-class-name: org.mariadb.jdbc.Driver
    username: goorm_bord
    password: goorm_bord1234

  # JPA 설정
  jpa:
    show-sql: true   # SQL 쿼리 콘솔에 출력
    hibernate:
      ddl-auto: update  # 또는 update (create는 매번 새로 생성)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true  # SQL 쿼리 포맷팅

  # Thymeleaf 설정
  thymeleaf:
    cache: false  # 개발시 템플릿 캐시 비활성화 (Hot Reload)